version: '2'
services:
  nogoodies-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/nogoodies/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=nogoodies
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
